[app]
title  = "Qwhizz: Learning Gamified "  
subtitle  = " - Built to grow with you 📈"    
subheader  = "Vineland Relief Society Lessons"   
icon   = "🗝🗝 "     
theme  = "rosegold"  
show_theme_switcher = true

[mongo]
uri = "mongodb+srv://rus19023_db_user:DI5bXFHgUztFHkG0@dna-study.w1xkbe0.mongodb.net/?retryWrites=true&w=majority&appName=dna-study"
db_name = "church_study"