[app]
title  = "Qwhizz: Learning Gamified "  
subtitle  = " - Built to grow with you 📈"    
subheader  = "DNA Study for BYU-I GESCI 205"   
icon   = "🧬🧬"
theme  = "retro"  
show_theme_switcher = true
theme_switcher_location = "sidebar" #TODO: Create a container in the app, in header maybe?  
show_icon_titles = "false"  
screen_width = "wide"
start_sidebar_state = "expanded"
cookie_password = "feelingDr@g0Npass4g3m0Nk3ypossesion"

[mongo]
uri = "mongodb+srv://rus19023_db_user:DI5bXFHgUztFHkG0@dna-study.w1xkbe0.mongodb.net/?retryWrites=true&w=majority&appName=dna-study"
db_name = "flashcards"

[email]

